"""create users table

Revision ID: 64a18fe78db6
Revises: 6061a338e515
Create Date: 2026-05-30 16:19:01.778454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a18fe78db6'
down_revision: Union[str, Sequence[str], None] = '6061a338e515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'category_image_url')
    # ### end Alembic commands ###
